--- sound/soc/codecs/Makefile
+++ sound/soc/codecs/Makefile
@@ -1,5 +1,6 @@
 CFLAGS_es325.o += -w
 CFLAGS_wcd9310.o += -w
+CFLAGS_wcd9304.o += -w
 
 snd-soc-88pm860x-objs := 88pm860x-codec.o
 snd-soc-ac97-objs := ac97.o
