--- drivers/input/touchscreen/Makefile
+++ drivers/input/touchscreen/Makefile
@@ -98,3 +98,4 @@ obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_TEST_REPORTING) += synaptics_dsx_test_rep
 obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_FW_UPDATE_MMI) += synaptics_dsx_fw_update.o
 obj-$(CONFIG_TOUCHSCREEN_TOUCHX)        += touchx.o
 obj-$(CONFIG_WAKE_GESTURES)		+= wake_gestures.o
+obj-$(CONFIG_STATE_NOTIFIER)		+= state_notifier.o
