--- security/Makefile
+++ security/Makefile
@@ -28,8 +28,3 @@ obj-$(CONFIG_CGROUP_DEVICE)		+= device_cgroup.o
 # Object integrity file lists
 subdir-$(CONFIG_INTEGRITY)		+= integrity
 obj-$(CONFIG_INTEGRITY)			+= integrity/built-in.o
-
-# TIMA uevent 
-ifeq ($(TIMA_ENABLED),1)
-obj-y     += tima_uevent/
-endif
