--- arch/arm/Makefile
+++ arch/arm/Makefile
@@ -264,6 +264,7 @@ core-$(CONFIG_VMWARE_MVP)	+= arch/arm/mvp/
 # If we have a machine-specific directory, then include it in the build.
 core-y				+= arch/arm/kernel/ arch/arm/mm/ arch/arm/common/
 core-y				+= arch/arm/net/
+core-y				+= arch/arm/crypto/
 core-y				+= $(machdirs) $(platdirs)
 
 drivers-$(CONFIG_OPROFILE)      += arch/arm/oprofile/
